[project]
name = "parsled"
version = "0.2.0"
requires-python = ">=3.8"
dependencies = []

description = "Parser and serializer for Sled, a serialization language for developer-friendly reading and writing"
readme = "README.md"
authors = [
  {name = "Kawin", email = "kawin.open@gmail.com"}
]
maintainers = [
  {name = "Kawin", email = "kawin.open@gmail.com"}
]
license = "MIT"
license-files = ["LICENSE"]

keywords = ["sled", "parse", "serialize", "deserialize", "readable", "language", "format"]
classifiers = [
  "Intended Audience :: Developers",
  "Topic :: File Formats",
  "Typing :: Typed",
]

[project.urls]
Homepage = "https://parsled.readthedocs.io"
Documentation = "https://parsled.readthedocs.io"
Source = "https://github.com/kawindex/sled/tree/main/python"
Issues = "https://github.com/kawindex/sled/issues"


[build-system]
requires = [ "uv_build>=0.10.12,<0.11.0" ]
build-backend = "uv_build"


[ dependency-groups ]
dev = [ "pytest<=9.0.3", "pytest-cov<=7.1.0" ]


[tool.pytest.ini_options]
pythonpath = "src"
addopts = [
  "--import-mode=importlib",
]
