name: Python test
on:
  workflow_call:

jobs:
  python-test:
    name: Python ${{ matrix.python-version }} test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
    env:
      UV_PYTHON: ${{ matrix.python-version }}
      UV_MANAGED_PYTHON: true
      USE_UV_VERSION: '0.11.6'

    steps:
      - name: Checkout python and testdata directories
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            python/
            testdata/

      - name: Log commit SHA
        run: 'echo "commit SHA: ${GITHUB_SHA}"'

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ env.USE_UV_VERSION }}
          python-version: ${{ matrix.python-version }}

      - name: Install Python
        working-directory: ${{ github.workspace }}/python
        run: uv python install ${{ matrix.python-version }}

      - name: Set up project environment
        working-directory: ${{ github.workspace }}/python
        run: uv sync

      - name: Run pytest py39-314
        if: '${{ ! startsWith( matrix.python-version, ''3.8'' ) }}'
        working-directory: ${{ github.workspace }}/python
        run: >
          uv run pytest
          --cov=parsled
          --cov-report=term-missing
          --cov-report="markdown-append:${GITHUB_STEP_SUMMARY}"
          tests/

      - name: Run pytest py38
        if: '${{ startsWith( matrix.python-version, ''3.8'' ) }}'
        run: 'bash "${GITHUB_WORKSPACE}/python/scripts/pytest_py38.sh"'

      - name: Run smoke test without dev dependencies
        working-directory: ${{ github.workspace }}/python
        run: 'uv run --no-dev "${GITHUB_WORKSPACE}/python/scripts/smoke_test.py"'
