name: Python PR check
on:
  pull_request:
    paths:
      - python/**
      - testdata/**
      - .github/**

jobs:
  invoke-python-test:
    name: Invoke Python test
    uses: ./.github/workflows/python-test.yml
